---
- name: install build-essential
  apt: pkg={{ item }}
       update_cache=yes
       cache_valid_time={{ common_apt_cache_valid_time }}
  with_items:
    - build-essential

- include: python.yml
- include: nodejs.yml
- include: git.yml

- name: install cssmin
  pip: name=cssmin
       executable={{ pip_binary }}

- name: install honcho
  pip: name=honcho
       executable={{ pip_binary }}

- name: install bower
  npm: name=bower
       global=yes

- name: install coffee-script
  npm: name=coffee-script
       global=yes

- name: install uglify-js
  npm: name=uglify-js
       global=yes

- name: install compass
  apt: pkg=ruby-compass
       update_cache=yes
       cache_valid_time={{ common_apt_cache_valid_time }}
