---
- name: install nodejs
  apt: pkg={{ item }}
       update_cache=yes
       cache_valid_time={{ common_apt_cache_valid_time }}
  with_items:
    - nodejs
    - npm

- name: link node executable
  file: path=/usr/local/bin/node
        src=/usr/bin/nodejs
        state=link
        owner=root group=root mode=0755
